######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 28 15:49:37 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mandelbrotwidget.h renderthread.h
SOURCES += main.cpp mandelbrotwidget.cpp renderthread.cpp
